---
- name: Asegurar que la auditoría de validación de credenciales registre 'Success and Failure'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría para validar credenciales
      win_shell: |
        $currentStatus = auditpol /get /subcategory:"Credential Validation" | Select-String -Pattern "Success and Failure"
        if (!$currentStatus) {
          auditpol /set /subcategory:"Credential Validation" /success:enable /failure:enable
          Write-Output "Política de auditoría configurada para 'Success and Failure'"
        } else {
          Write-Output "La política de auditoría ya está configurada para 'Success and Failure'"
        }
      register: audit_result

    - name: Verificar que la política se configuró correctamente
      debug:
        msg: "{{ audit_result.stdout }}"
