---
- name: Asegurar que la auditoría de validación de credenciales registre 'Success and Failure'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría de Validación de credenciales
      win_shell: auditpol /set /subcategory:”Validación de credenciales" /success:enable /failure:enable
