---
- name: Asegurar que la auditoría de Operaciones de vales de servicio Kerberos registre 'Success'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Operaciones de vales de servicio Kerberos
      win_shell: auditpol /set /subcategory:"Operaciones de vales de servicio Kerberos" /success:enable /failure:enable
    
