- name: Asegurar que la auditoría de las operaciones de tickets de servicio Kerberos registre 'Success and Failure'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría de las operaciones de tickets de servicio Kerberos
      win_shell: auditpol /set /subcategory:"Auditoría de las operaciones de tickets de servicio Kerberos" /success:enable /failure:enable
