---
- name: Asegurar que la auditoría de Administración de cuentas de equipo registre 'Success'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Administración de cuentas de equipo
      win_shell: auditpol /set /subcategory:"Administración de cuentas de equipo" /success:enable
