---
- name: Configurar la auditoría de gestión de grupos de aplicaciones para 'Success and Failure'
  hosts: all
  gather_facts: no

  tasks:
    - name: Verificar la configuración actual para 'Audit Application Group Management'
      win_shell: |
        $currentStatus = auditpol /get /subcategory:"Application Group Management" | Select-String -Pattern "Success and Failure"
        if (!$currentStatus) {
          auditpol /set /subcategory:"Application Group Management" /success:enable /failure:enable
          Write-Output "Configuración de auditoría ajustada a 'Success and Failure'"
        } else {
          Write-Output "La auditoría ya está configurada para 'Success and Failure'"
        }
      register: audit_result

    - name: Verificar que la configuración se realizó correctamente
      debug:
        msg: "{{ audit_result.stdout }}"
