- name: Asegurar que la auditoría de 'Audit Distribution Group Management' registre 'Success'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría de 'Audit Distribution Group Management'
      win_shell: auditpol /set /subcategory:"Distribution Group Management" /success:enable
