---
- name: Asegurar que la auditoría de gestión de grupos de aplicaciones registre 'Success and Failure'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría de gestión de grupos de aplicaciones
      win_shell: auditpol /set /subcategory:”gestión de grupos de aplicaciones” /success:enable /failure:enable
