---
- name: Asegurar que la auditoría de Eventos Plug and Play registre 'Success'
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría de Eventos Plug and Play
      win_shell: auditpol /set /subcategory:”Eventos Plug and Play” /success:enable
