---
- name: Asegurar que la auditoría de Cerrar sesión registre ’Success’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Cerrar sesión
      win_shell: auditpol /set /subcategory:”Cerrar sesión” /success:enable
