---
- name: Asegurar que la auditoría de Bloqueo de cuenta registre ‘Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Bloqueo de cuenta
      win_shell: auditpol /set /subcategory:”Bloqueo de cuenta” /failure:enable
