---
- name: Asegurar que la auditoría de Otros eventos de inicio y cierre de sesión registre ’Success y Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Otros eventos de inicio y cierre de sesión
      win_shell: auditpol /set /subcategory:”Otros eventos de inicio y cierre de sesión” /success:enable /failure:enable
