---
- name: Asegurar que la auditoría de Otros eventos de acceso a objetos registre ’Success and Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Otros eventos de acceso a objetos
      win_shell: auditpol /set /subcategory:”Otros eventos de acceso a objetos” /success:enable /failure:enable
