---
- name: Asegurar que la auditoría de Recurso compartido de archivos detallado registre ’Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Recurso compartido de archivos detallado
      win_shell: auditpol /set /subcategory:”Recurso compartido de archivos detallado” /failure:enable
