---
- name: Configurar la auditoría para 'Audit Detailed File Share' para 'Failure'
  hosts: all
  gather_facts: no

  tasks:
    - name: Verificar la configuración actual para 'Audit Detailed File Share'
      win_shell: |
        $currentStatus = auditpol /get /subcategory:"Detailed File Share" | Select-String -Pattern "Failure"
        if (!$currentStatus) {
          auditpol /set /subcategory:"Detailed File Share" /failure:enable
          Write-Output "Configuración de auditoría ajustada a 'Failure'"
        } else {
          Write-Output "La auditoría ya está configurada para 'Failure'"
        }
      register: audit_result

    - name: Confirmar que la configuración se realizó correctamente
      debug:
        msg: "{{ audit_result.stdout }}"
