---
- name: Asegurar que la auditoría de Audit Cambio de la directiva de autenticación registre Success
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría a Cambio de la directiva de autenticación
      win_shell: auditpol /set /subcategory:"Cambio de la directiva de autenticación" /success:enable /failure:enable
