---
- name: Asegurar que la auditoría de Otros eventos de cambio de directivas registre ’Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Otros eventos de cambio de directivas
      win_shell: auditpol /set /subcategory:”Otros eventos de cambio de directivas” /failure:enable
