---
- name: Asegurar que la auditoría de Cambio en la directiva de auditoría registre ’Success’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Cambio en la directiva de auditoría
      win_shell: auditpol /set /subcategory:”Cambio en la directiva de auditoría” /success:enable
