---
- name: Asegurar que la auditoría de Controlador de IPsec registre ’Success and Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Controlador de IPsec
      win_shell: auditpol /set /subcategory:”Controlador de IPsec” /success:enable /failure:enable
