---
- name: Asegurar que la auditoría de Uso de privilegio confidencial ’Success and Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Uso de privilegio confidencial
      win_shell: auditpol /set /subcategory:”Uso de privilegio confidencial” /success:enable /failure:enable
