--
- name: Asegurar que la auditoría Integridad del sistema registre ’Success and Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política auditoría de Integridad del sistema
      win_shell: auditpol /set /subcategory:”Integridad del sistema” /success:enable /failure:enable
