---
- name: Asegurar que la auditoría de Cambio de estado de seguridad registre ’Success’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría Cambio de estado de seguridad
      win_shell: auditpol /set /subcategory:”Cambio de estado de seguridad” /success:enable
