---
- name: Asegurar que la auditoría de Controlador IPsec ’Success and Failure’
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar la política de auditoría de Controlador IPsec
      win_shell: auditpol /set /subcategory:”Controlador IPsec” /success:enable /failure:enable
