- name: Ensure 'Prevent enabling lock screen camera' policy is set and 'Audit Security System Extension' audit policy is set to record Success
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure 'Prevent enabling lock screen camera' policy
      win_regedit:
        path: HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization
        name: PreventLockScreenCamera
        data: 1
        state: present
      register: camera_lock_result

    - name: Verify the result of the security policy configuration
      debug:
        msg: "{{ camera_lock_result }}"

    - name: Configure 'Audit Security System Extension' audit policy to record Success
      win_shell: auditpol /set /subcategory:"Security System Extension" /success:enable
      register: audit_policy

    - name: Print the audit policy result
      debug:
        msg: "Audit policy for 'Security System Extension' set to record Success: {{ audit_policy.changed }}"
