- name: Ensure 'Prevent enabling lock screen camera' policy is set and 'Audit Security System Extension' audit policy is set to record Success
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure 'Prevent enabling lock screen camera' policy
      win_command: |
        $regPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization"
        $regName = "PreventLockScreenCamera"
        $regValue = 1
        
        if (!(Test-Path $regPath)) {
            New-Item -Path $regPath -Force | Out-Null
        }
        
        Set-ItemProperty -Path $regPath -Name $regName -Value $regValue
      register: camera_lock_result

    - name: Verify the result of the security policy configuration
      debug:
        msg: "{{ camera_lock_result }}"

    - name: Configure 'Audit Security System Extension' audit policy to record Success
      win_shell: auditpol /set /subcategory:"Security System Extension" /success:enable
      register: audit_policy

    - name: Print the audit policy result
      debug:
        msg: "Audit policy for 'Security System Extension' set to record Success: {{ audit_policy.changed }}"
