- name: Ensure 'Password Settings: Password Length' is set to 'Enabled: 15 or more'
  hosts: all
  gather_facts: no
  tasks:
    - name: Check current status of 'Password Settings: Password Length'
      win_command: secedit /export /cfg C:\temp\security.txt
      ignore_errors: yes

    - name: Modify security template to set 'Password Settings: Password Length' to 'Enabled: 15 or more'
      win_shell: |
        (Get-Content C:\temp\security.txt).replace('PasswordLength = 14', 'PasswordLength = 15') | Set-Content C:\temp\security.txt
      ignore_errors: yes

    - name: Apply the modified security template
      win_command: secedit /configure /db %windir%\security\new.sdb /cfg C:\temp\security.txt /areas SECURITYPOLICY
      ignore_errors: yes

    - name: Verify the configuration of 'Password Settings: Password Length'
      win_command: secedit /export /cfg C:\temp\security_verification.txt
      ignore_errors: yes

    - name: Display the result of the configuration
      debug:
        msg: "'Password Settings: Password Length' is configured as {{ lookup('file', 'C:/temp/security_verification.txt') }}"
