- name: Ensure 'Enable Local Admin Password Management' is set to 'Enabled'
  hosts: all
  gather_facts: no
  tasks:
    - name: Check current status of 'Enable Local Admin Password Management'
      win_command: Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"
      register: enable_lapm_status
      ignore_errors: yes

    - name: Enable 'Enable Local Admin Password Management' if not already enabled
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: EnableLUA
        data: 1
        type: dword
        state: present
      when: enable_lapm_status.stdout != "1"  # Assuming '1' means 'Enabled'

    - name: Verify the configuration of 'Enable Local Admin Password Management'
      win_command: Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"
      register: verify_lapm_status

    - name: Display the result of the configuration
      debug:
        msg: "'Enable Local Admin Password Management' is configured as {{ verify_lapm_status.stdout | default('Not configured') }}"
