- name: Instalar LAPS AdmPwd GPO Extension / CSE
  hosts: all
  gather_facts: no
  tasks:
    - name: Verificar si LAPS AdmPwd GPO Extension / CSE está instalado
      win_shell: |
        $featureName = "RSAT-AD-PowerShell"
        $feature = Get-WindowsFeature -Name $featureName
        $feature.Installed
      register: laps_feature_status
      changed_when: false

    - debug:
        var: laps_feature_status

    - name: Instalar LAPS AdmPwd GPO Extension / CSE si no está instalado
      win_shell: |
        $featureName = "RSAT-AD-PowerShell"
        $feature = Get-WindowsFeature -Name $featureName
        if (!$feature.Installed) {
          Install-WindowsFeature -Name $featureName -IncludeAllSubFeature -IncludeManagementTools
        }
      when: not laps_feature_status.stdout | bool

    - name: Verificar que LAPS AdmPwd GPO Extension / CSE se instaló correctamente
      win_shell: |
        $featureName = "RSAT-AD-PowerShell"
        $feature = Get-WindowsFeature -Name $featureName
        $feature.Installed
      register: laps_feature_verification

    - name: Mostrar el resultado de la instalación
      debug:
        msg: "La extensión / CSE de LAPS se instaló: {{ laps_feature_verification.stdout }}"
