- hosts: all
  tasks:
    - name: Set 'Password Settings: Password Length' policy
      win_security_policy:
        section: System Access
        key: MinimumPasswordLength
        value: "15"

    - name: Get 'Password Settings: Password Length' policy
      win_security_policy:
        section: System Access
        key: MinimumPasswordLength
      register: password_length_policy

    - name: Print result
      debug:
        msg: "Password Length policy set to 15 or more characters: {{ password_length_policy.value }}"
