- hosts: all
  tasks:
    - name: Set 'Password Settings: Password Length' policy
      win_shell: |
        $securityPolicy = [Microsoft.Security.Policy.SecurityPolicy]::new()
        $securityPolicy.SystemAccess.MinimumPasswordLength = 15
        $securityPolicy.Save()
      register: set_password_length

    - name: Get 'Password Settings: Password Length' policy
      win_shell: |
        $securityPolicy = [Microsoft.Security.Policy.SecurityPolicy]::new()
        $securityPolicy.Load()
        $securityPolicy.SystemAccess.MinimumPasswordLength
      register: get_password_length_policy

    - name: Print result
      debug:
        msg: "Password Length policy set to 15 or more characters: {{ get_password_length_policy.stdout }}"
