- hosts: all
  tasks:
    - name: Check current 'Password Settings: Password Length' policy
      win_shell: |
        $securityPolicy = [Microsoft.Security.Policy.SecurityPolicy]::new()
        $securityPolicy.Load()
        $securityPolicy.SystemAccess.MinimumPasswordLength
      register: current_password_length

    - name: Set 'Password Settings: Password Length' policy to 15 or more characters
      win_shell: |
        $securityPolicy = [Microsoft.Security.Policy.SecurityPolicy]::new()
        $securityPolicy.Load()
        $securityPolicy.SystemAccess.MinimumPasswordLength = 15
        $securityPolicy.Save()
      when: current_password_length.stdout | int < 15

    - name: Verify 'Password Settings: Password Length' policy is set to 15 or more characters
      win_shell: |
        $securityPolicy = [Microsoft.Security.Policy.SecurityPolicy]::new()
        $securityPolicy.Load()
        $securityPolicy.SystemAccess.MinimumPasswordLength
      register: verified_password_length

    - name: Display the result
      debug:
        msg: "Password Length policy is set to {{ verified_password_length.stdout }} characters"
