- name: Ensure 'Enable Local Admin Password Management' is set to 'Enabled'
  hosts: all
  gather_facts: no
  tasks:
    - name: Check current status of 'Enable Local Admin Password Management'
      win_shell: |
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
        if (Test-Path -Path $regPath) {
            $regValue = (Get-ItemProperty -Path $regPath -Name "EnableLUA" -ErrorAction SilentlyContinue).EnableLUA
            $regValue
        } else {
            Write-Output "Not configured"
        }
      register: enable_lapm_status
      changed_when: false

    - name: Enable 'Enable Local Admin Password Management' if not already enabled
      win_shell: |
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
        if (!(Test-Path -Path $regPath)) {
            New-Item -Path $regPath -Force | Out-Null
        }
        Set-ItemProperty -Path $regPath -Name "EnableLUA" -Value 1
      when: enable_lapm_status.stdout != "1"  # Assuming '1' means 'Enabled'

    - name: Verify the configuration of 'Enable Local Admin Password Management'
      win_shell: |
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"
        if (Test-Path -Path $regPath) {
            (Get-ItemProperty -Path $regPath -Name "EnableLUA" -ErrorAction SilentlyContinue).EnableLUA
        } else {
            Write-Output "Not configured"
        }
      register: verify_lapm_status

    - name: Display the result of the configuration
      debug:
        msg: "'Enable Local Admin Password Management' is configured as {{ verify_lapm_status.stdout }}"
