- name: Instalar LAPS AdmPwd GPO Extension / CSE
  hosts: all
  gather_facts: no
  tasks:
    - name: Verificar si LAPS AdmPwd GPO Extension / CSE está instalado
      win_feature:
        name: RSAT-AD-PowerShell  # Assuming the name of LAPS feature is RSAT-AD-PowerShell
      register: laps_feature_status

    - debug:
        var: laps_feature_status

    - name: Instalar LAPS AdmPwd GPO Extension / CSE si no está instalado
      win_feature:
        name: RSAT-AD-PowerShell  # Assuming the name of LAPS feature is RSAT-AD-PowerShell
        state: present
      when: laps_feature_status.feature_result | length == 0 or laps_feature_status.feature_result[0].state == 'absent'

    - name: Verificar que LAPS AdmPwd GPO Extension / CSE se instaló correctamente
      win_feature:
        name: RSAT-AD-PowerShell  # Assuming the name of LAPS feature is RSAT-AD-PowerShell
      register: laps_feature_verification

    - name: Mostrar el resultado de la instalación
      debug:
        msg: "La extensión / CSE de LAPS se instaló: {{ laps_feature_verification.results[0].state }}"

