---
- name: Change Windows Firewall Domain profile outbound connections to Allow
  hosts: all
  gather_facts: no
  tasks:
    - name: Set Windows Firewall Domain profile outbound connections to Allow
      ansible.windows.win_shell: |
        # Define the PowerShell script to set the outbound connection action to Allow
        Set-NetFirewallProfile -Profile Domain -DefaultOutboundAction Allow

      register: firewall_domain_outbound_result

    - name: Check if firewall setting was changed
      debug:
        msg: "Firewall outbound connections setting was {{ 'changed' if firewall_domain_outbound_result.changed else 'unchanged' }}"

    - name: Notify on listening settings
      ansible.windows.win_shell: |
        # Enable notifications on listening for the Domain profile
        Set-NetFirewallProfile -Profile Domain -NotifyOnListen $true

      when: firewall_domain_outbound_result.changed
