---
- name: Ensure 'Windows Firewall: Domain: Outbound connections' is set to 'Allow (default)'
  hosts: all
  gather_facts: no
  tasks:
    - name: Get the current Windows Firewall domain profile settings
      win_shell: Get-NetFirewallProfile -Profile Domain
      register: domain_firewall_profile

    - name: Ensure 'Windows Firewall: Domain: Outbound connections' is set to 'Allow (default)'
      win_firewall_rule:
        name: 'Windows Firewall: Domain: Outbound connections'
        direction: out
        action: allow
        state: present
      when: domain_firewall_profile.stdout.find('DefaultOutboundAction   : Block') != -1
