- hosts: all
  tasks:
    - name: Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'
      win_shell: |
        $firewallProfile = Get-NetFirewallProfile -Name Domain
        if ($firewallProfile.Enabled -ne $true) {
            Set-NetFirewallProfile -Name Domain -Enabled True
        }
      register: firewall_state
      changed_when: firewall_state.stdout.contains("Enabled")
      failed_when: not firewall_state.stdout.contains("Enabled")
      tags:
        - firewall
        - security
