---
- name: Ensure 'Windows Firewall: Domain: Outbound connections' is set to 'Allow (default)'
  hosts: all
  gather_facts: no

  tasks:
    - name: Get the current Windows Firewall domain profile settings
      win_shell: Get-NetFirewallProfile -Profile Domain
      register: domain_firewall_profile

    - name: Set 'Windows Firewall: Domain: Outbound connections' to 'Allow (default)'
      win_shell: |
        Set-NetFirewallProfile -Profile Domain -DefaultOutboundAction Allow
