---
- name: Cambiar políticas de contraseñas en Windows Server (WindowsFirewallPrivateInbound)
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil de Dominio
      win_shell: Get-NetFirewallProfile -Profile Domain

    - name: Modificar política de WindowsFirewallPrivateInbound
      win_shell: Set-NetFirewallProfile -Profile Private -DefaultInboundAction Block
