---
- name: Cambiar políticas de contraseñas en Windows Server (WindowsFirewallPrivateOutbound)
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil de Dominio
      win_shell: Get-NetFirewallProfile -Profile Private

    - name: Modificar política de WindowsFirewallPrivateOutbound
      win_shell: Set-NetFirewallProfile -Profile Private -DefaultOutboundAction Allow
