---
- name: Cambiar configuraciones del Firewall (WindowsFirewallPrivateLoggingLogSuccessfulConnections)
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil Privado
      win_shell: Get-NetFirewallProfile -Profile Private

    - name: Modificar política de WindowsFirewallPrivateLoggingLogSuccessfulConnections
      win_shell: Set-NetFirewallProfile -Profile Private -LogAllowed True
