- hosts: windows_servers
  tasks:
    - name: Ensure Windows Firewall Private Profile Outbound Connections is set to 'Allow (default)'
      win_shell: |
        $profile = Get-NetFirewallProfile -Profile Private
        if ($profile.DefaultOutboundAction -ne "Allow") {
            Set-NetFirewallProfile -Profile Private -DefaultOutboundAction Allow
            Write-Output "Windows Firewall Private Profile Outbound Connections set to 'Allow (default)'"
        } else {
            Write-Output "Windows Firewall Private Profile Outbound Connections already set to 'Allow (default)'"
        }
      register: firewall_config
      changed_when: firewall_config.rc == 0
