---
- name: Cambiar políticas de contraseñas en Windows Server
  hosts: all
  gather_facts: no
  tasks:
    - name: Set Windows Firewall Private Profile Outbound connections to Allow
      win_firewall_profile:
        profile: private
        default_outbound_action: allow
        state: present
