- name: Cambiar políticas de contraseñas en Windows Server 
  hosts: all
  gather_facts: no
  tasks:
    - name: Set Windows Firewall Private Profile Outbound connections to Allow
      win_firewall_rule:
        profile: private
        name: "Allow Outbound Connections"
        enabled: yes
