---
- name: Cambiar políticas de contraseñas en Windows Server (WindowsFirewallPrivateSettingsDisplayNotification)
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil de Dominio
      win_shell: Get-NetFirewallProfile -Profile Private

    - name: Modificar política de WindowsFirewallPrivateSettingsDisplayNotification
      win_shell: Set-NetFirewallProfile -Profile Private -NotifyOnListen True
