---
- name: Cambiar configuraci칩n de firewall en Windows Server
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuraci칩n actual del perfil de firewall privado
      win_shell: Get-NetFirewallProfile -Profile Private
      register: firewall_private_profile

    - name: Establecer ruta de registro para el perfil privado
      win_shell: |
        Set-NetFirewallProfile -Profile Private -LogFileName "%SystemRoot%\\System32\\logfiles\\firewall\\privatefw.log"
      when: "'LogFileName' not in firewall_private_profile.stdout or '%SystemRoot%\\System32\\logfiles\\firewall\\privatefw.log' not in firewall_private_profile.stdout"
    
    - name: Asegurar la ruta de registro en el perfil privado
      win_shell: Get-NetFirewallProfile -Profile Private
      register: updated_firewall_private_profile

    - name: Comprobar que la ruta de registro est치 configurada correctamente
      assert:
        that:
          - "'%SystemRoot%\\System32\\logfiles\\firewall\\privatefw.log' in updated_firewall_private_profile.stdout"
        fail_msg: "La ruta de registro para el perfil privado no est치 configurada correctamente."

    - name: Desactivar notificaciones de escucha en el perfil privado
      win_shell: Set-NetFirewallProfile -Profile Private -NotifyOnListen False
