---
- name: Configurar el registro de paquetes descartados en Firewall (Perfil Privado)
  hosts: all
  gather_facts: no

  tasks:
    - name: Establecer valor para 'Log dropped packets' (Perfil Privado)
      win_regedit:
        path: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PrivateProfile\Logging\LogDroppedPackets'
        name: '(Default)'
        data: '1'  # '1' para habilitar, '0' para deshabilitar
        datatype: 'dword'
      register: result

    - name: Verificar si la configuración se aplicó correctamente
      debug:
        msg: "El registro de paquetes descartados para el perfil privado del firewall está habilitado."
      when: result.changed
