---
- name: Asegurar que las reglas de firewall locales no se apliquen (Perfil Público)
  hosts: all
  gather_facts: no
  tasks:
    - name: Verificar la configuración actual para 'Apply local firewall rules' en el perfil público
      win_shell: |
        $profile = Get-NetFirewallProfile -Profile Public
        $profile.AllowLocalFirewallRules
      register: allow_local_rules_status

    - name: Establecer 'Apply local firewall rules' para 'No'
      win_shell: Set-NetFirewallProfile -Profile Public -AllowLocalFirewallRules False
      when: allow_local_rules_status.stdout != 'False'

    - name: Confirmar que las reglas de firewall locales no se aplican en el perfil público
      debug:
        msg: "Las reglas de firewall locales no se aplican en el perfil público."
      when: allow_local_rules_status.stdout == 'False'
