---
- name: Cambiar configuraciones del Firewall (WindowsFirewallPublicSettingsDisplayNotification)
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil Public
      win_shell: Get-NetFirewallProfile -Profile Public

    - name: Habilitar registro de paquetes descartados en el perfil Público
      win_shell: Set-NetFirewallProfile -Profile Public -LogFileName "%SystemRoot%\System32\LogFiles\Firewall\pfirewall.log" -LogMaxSizeKilobytes 16384 -LogAllowed Yes -LogBlocked Yes
