---
- name: Cambiar configuraciones del Firewall (WindowsFirewallPublicLoggingSizeLimit(KB))
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil Public
      win_shell: Get-NetFirewallProfile -Profile Public

    - name: Modificar política de WindowsFirewallPublicLoggingSizeLimit(KB))
      win_shell: Set-NetFirewallProfile -Profile Public -LogMaxSizeKilobytes 16384
