---
- name: Asegurar que el firewall del perfil público registre paquetes descartados
  hosts: all
  gather_facts: no

  tasks:
    - name: Verificar la configuración actual para el registro de paquetes descartados
      win_shell: |
        $profile = Get-NetFirewallProfile -Profile Public
        (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile\Logging').LogDroppedPackets
      register: log_dropped_packets_status

    - name: Configurar para registrar paquetes descartados
      win_regedit:
        path: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile\Logging'
        name: 'LogDroppedPackets'
        data: '1'
        datatype: 'dword'
      when: log_dropped_packets_status.stdout.strip() != '1'

    - name: Confirmar que el registro de paquetes descartados está habilitado
      debug:
        msg: "El registro de paquetes descartados para el perfil público está activado."
      when: log_dropped_packets_status.stdout.strip() == '1'
