---
- name: Asegurar que el firewall del perfil público registre paquetes descartados
  hosts: all
  gather_facts: no

  tasks:
    - name: Establecer 'Log dropped packets' en el perfil público
      win_regedit:
        path: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile\Logging'
        name: 'LogDroppedPackets'
        data: '1'  # 1 para activar el registro de paquetes descartados
        datatype: 'dword'
      register: result

    - name: Confirmar que el registro de paquetes descartados está habilitado
      debug:
        msg: "El registro de paquetes descartados para el perfil público está activado."
      when: result.changed
