---
- name: Cambiar configuraciones del Firewall (WindowsFirewallPublicLoggingLogSuccessfulConnections)
  hosts: all
  gather_facts: no
  tasks:
    - name: Ver la configuración actual de las conexiones entrantes en el perfil Public
      win_shell: Get-NetFirewallProfile -Profile Public

    - name: Modificar política de WindowsFirewallPublicLoggingLogSuccessfulConnections
      win_shell: Set-NetFirewallProfile -Profile Public -LogAllowed True
